services:
  db-stravastats:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: stravastats
      POSTGRES_PASSWORD: stravastats
      POSTGRES_DB: stravastats
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: